name: regularized-linear-regression
channels:  
    - conda-forge
dependencies:  
    - python=3.8.18
    - numpy=1.24.3
    - pandas=2.0.3
    - Matplotlib=3.7.2
    - scikit-learn=1.3.2
    - seaborn=0.9.0
